rules:
  cache-poisoning:
    ignore:
      - 'pyinstaller.yml'
  dangerous-triggers:
    ignore:
      - 'publish-winget.yml'
      - 'release.yml'
  superfluous-actions:
    ignore:
      - 'flatpak.yml'
