######################################################################
# Automatically generated by qmake (2.01a) Mon May 3 06:53:27 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += cp437.h nfoviewer.h
SOURCES += cp437.cpp main.cpp nfoviewer.cpp qrc_nfoviewer.cpp
